# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: servlao 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = 'servlao'
  s.version = '0.0.1'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']
  s.authors = ['Vlad Shmyhlo']
  s.date = '2015-09-03'
  s.description = 'Very simple http service'
  s.email = 'aion.stu@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.rdoc'
  ]
  s.files = [
    '.document',
    '.rspec',
    '.ruby-gemset',
    '.ruby-version',
    'Gemfile',
    'Gemfile.lock',
    'LICENSE.txt',
    'README.rdoc',
    'Rakefile',
    'lib/servlao.rb',
    'lib/servlao/base.rb',
    'lib/servlao/base/config.rb',
    'lib/servlao/errors.rb',
    'lib/servlao/errors/configuration_missing.rb',
    'lib/servlao/errors/servlao_error.rb',
    'lib/servlao/version.rb',
    'servlao.gemspec',
    'spec/servlao_spec.rb',
    'spec/spec_helper.rb'
  ]
  s.homepage = 'http://github.com/v-shmyhlo/servlao'
  s.licenses = ['MIT']
  s.rubygems_version = '2.4.8'
  s.summary = 'Simple http service'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('typhoeus', ['>= 0'])
      s.add_development_dependency('rspec', ['~> 2.8.0'])
      s.add_development_dependency('rdoc', ['~> 3.12'])
      s.add_development_dependency('bundler', ['~> 1.0'])
      s.add_development_dependency('jeweler', ['~> 2.0.1'])
      s.add_development_dependency('simplecov', ['>= 0'])
      s.add_development_dependency('rubocop', ['>= 0'])
      s.add_development_dependency('pry', ['>= 0'])
    else
      s.add_dependency('typhoeus', ['>= 0'])
      s.add_dependency('rspec', ['~> 2.8.0'])
      s.add_dependency('rdoc', ['~> 3.12'])
      s.add_dependency('bundler', ['~> 1.0'])
      s.add_dependency('jeweler', ['~> 2.0.1'])
      s.add_dependency('simplecov', ['>= 0'])
      s.add_dependency('rubocop', ['>= 0'])
      s.add_dependency('pry', ['>= 0'])
    end
  else
    s.add_dependency('typhoeus', ['>= 0'])
    s.add_dependency('rspec', ['~> 2.8.0'])
    s.add_dependency('rdoc', ['~> 3.12'])
    s.add_dependency('bundler', ['~> 1.0'])
    s.add_dependency('jeweler', ['~> 2.0.1'])
    s.add_dependency('simplecov', ['>= 0'])
    s.add_dependency('rubocop', ['>= 0'])
    s.add_dependency('pry', ['>= 0'])
  end
end
